OPTIONS (SKIP=1, ERRORS=1000000, DIRECT=TRUE)
LOAD DATA
INFILE 'pliki-csv/panstwo.csv'
DISCARDFILE 'panstwo.dsc'
APPEND
INTO TABLE "panstwo"
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
	"panstwo_id" CHAR, 
	"nazwa" CHAR
)
